dhis2/maintenance-app-beta

- src/Maintenance.app.js
- src/components/Navigation.js
- src/components/Navigation/NavigationLink.js
- src/components/Sidebar.js
- src/components/authorization/ProtectedLink.js
- src/components/authorization/ProtectedRoute.js
- src/constants/sections.js
- src/utils/authority/hasUserAuthorityForSection.js
Currently the `schemaName` in the `sections.js` matches the property key of the section, but I think there will be some irregularities. Until I've figured them out, and them decide on a proper way to refactor it, I'd propose we just leave it as is for now
> feat: use api to determine required user privileges for sections

- i18n/en.pot
- src/app/layout/Layout.module.css
- src/app/layout/Layout.tsx
- src/app/routes/Router.tsx
- src/app/routes/types.ts
- src/pages/dataElements/New.module.css
Adds support for a footer in `layout`. Previously the `scrollbar` would disappear under the footer if a fixed footer was rendered. Note that this just intended to "reserve" the space in the grid, and the intention is that the form should render a `position: fixed`- component at the bottom of the page. The reason for this is that it's annoying to form-controls outside of the form.
> fix(layout): support fixed footer

- src/app/layout/Layout.module.css
- src/app/layout/PageTitle.tsx
- src/app/layout/index.tsx
- src/components/sectionList/SectionListTitle.tsx
- src/components/sectionList/SectionListWrapper.tsx
Implements `PageTitle` for `SectionList`. I was a bit unsure if this should've been another `handle`, and thus tied to the route. However, I think it might be more flexible composing it in the components that render it. Since for `Edit`-routes, the title depends on the object being edited (eg. `Edit: ANC 1st visit`). However, it comes with the downside of having to "manually" add these to the "wrapper"-components.
> fix(sectionlist): add page title

- src/pages/dataElements/Edit.tsx
- src/pages/dataElements/edit/createJsonPatchOperations.spec.ts
- src/pages/dataElements/edit/createJsonPatchOperations.ts
JSON-patch does not support patching nested fields in complex objects. So I added some logic to include that when "sanitizing" the keys - so they're sent together as a `style` object. 
EDIT:
Refactored and simplified `sanitizeDirtyValueKeys`
I've made the types a bit safer.
Also we sent too much information in attributes, simplified these to just send the id and value.
I do think we can use `schemas` and generalize this a bit more later.
> fix(form): fix editing style object

- src/pages/overview/card/SummaryCard.module.css
- src/pages/overview/card/SummaryCard.tsx
This PR adjusts the summary card component design:
- removes `Card` usage (may be deprecated from UI, so will not start using here)
- removes icons (not adding value, can revisit if we want to spend time making many unique icons, but is a tough task.)
- makes clickable area boundaries and interactions clearer
- adjusts styling
Before:
After:
> fix(summarycard): adjust icon-less design

- i18n/en.pot
- src/components/LinkButton/LinkButton.module.css
- src/components/LinkButton/LinkButton.tsx
- src/components/LinkButton/index.ts
- src/components/sectionList/SectionListRow.tsx
- src/components/sectionList/SectionListWrapper.tsx
- src/components/sectionList/listActions/SectionListActions.module.css
- src/components/sectionList/listActions/SectionListActions.tsx
https://dhis2.atlassian.net/browse/DHIS2-15561?filter=10364
> feat(list): context menu

- src/components/ColorAndIconPicker/useIconsQuery.ts
- src/types/generated/utility.ts
List API for icons has changed in 2.41. It's now a paginated response. There's currently still issues with the API, so we will have to update the app to support the pagination part later. But this fixes so that the form doesn't crash due to wrong response.
> fix(edit): fix icons api response

- src/components/sectionList/filters/filterSelectors/IdentifiableFilter.tsx
Refactored the debounce to use a callback instead of `useEffect`. The `useEffect` would run on initial render and cause the filter to be reset.
> fix(list): fix filter being cleared on refresh

- src/lib/systemSettings/systemSettingsStore.tsx
Very minor typefix, so that we get the actual type of a particular setting instead of the union of all settings.
> fix(systemSettings): use generic type for setting inference

- .github/workflows/dhis2-verify-app.yml
- src/pages/DefaultSectionList.tsx
Add a check for  running type-checks before building. However, I'm not sure if it's best to
1. Check types in as a step in `build`-job
* This means we don't build at all if the type-check fails, in my opinion we shouldn't build at all if type-checking fails.
2. Check types as a step in `lint`-job.
* This means build will still run.  
3. Check types as it's own job
* Imo the least attractive option for now, as it's adds another runner and needs to install deps etc. Could be useful if we want more complex step to run conditionally whether it's a TS-app or not. 
4. Just add it in `package.json` "build"-script; `"build": "yarn check-types && d2-app-scripts build"`
* This would mean no changes to workflow, but can be annoying if you eg. want to pass arguments to build.
> chore(workflow): check types before build

- src/components/metadataFormControls/CategoryComboSelect/CategoryComboSelect.test.tsx
- src/components/metadataFormControls/CategoryComboSelect/useInitialOptionQuery.ts
- src/components/metadataFormControls/CategoryComboSelect/useOptionsQuery.ts
- src/lib/constants/defaultModelObjects.ts
- src/lib/constants/index.ts
- src/pages/dataElements/New.spec.tsx
- src/pages/dataElements/New.tsx
- src/pages/dataElements/__mocks__/categoryCombosPage1.json
We should default to the `default categoryCombo` when creating a Data Element. The default-catergory combo ID is hardcoded on the backend, so it's safe to use the static id. This makes it much easier compared to having to fetch that cat-combo, because we can statically set it on the initialValues. This feels a bit weird, but I've talked to Jason about it, and he said this is totally fine. If we don't want to this, we should instead load it on app-load to free up components that reference it from additional loading states. 
Some changes in CategoryComboSelect:
1. Updated filters so we never fetch default
2. Don't fetch initialValue if the select-value is default (we already have that info)
3. Always add the "None" to the list
* None (default-catcombo) is effectively "clearing the select". …
> fix(dataElement): default to default-cat-combo

- .github/workflows/dhis2-verify-app.yml
- cypress/e2e/dataElements/New.spec.ts
- src/components/ColorAndIconPicker/ColorPicker.tsx
- src/components/ColorAndIconPicker/IconPicker.tsx
Color and Icon buttons were changed to `button` without `type=button`, this means they were submit-buttons and those submitted the form when clicked.
> fix: fix cypress tests and color/icon buttons

- .github/workflows/dhis2-verify-app.yml
- package.json
- src/app/layout/Breadcrumb.module.css
- src/components/ColorAndIconPicker/IconPickerModal.module.css
- src/components/SearchableSingleSelect/SearchableSingleSelect.module.css
- src/components/loading/Loader.module.css
- src/components/sectionList/download/DownloadDialog.module.css
- src/components/sectionList/listActions/DeleteAction.module.css
- src/components/sectionList/toolbar/Toolbar.module.css
- src/pages/overview/group/OverviewGroup.module.css
- src/testUtils/TestComponentWithRouter.tsx
- yarn.lock
Part of this ticket:
Upgrading dhis2 packages (which will pick up the fix for v41+ logins): https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-17941
This PR updates our @dhis2/cli-app-scripts (major version upgrade from 10 to 11); I've reinstalled dhis2/ui to prevent conflicting versions between the app and the shell, and I've also run `yarn upgrade` on the remaining dhis2 packages (minor version updates).
I assume something maybe changed in cli-style to pick up the css files on lint because some of these came back as having formatting problems after update, so I've rerun that (the other change you'll see in this PR).
The dependency updates also mean that they are not compatible with node v16, so I've updated the workflows to use v20.
> chore: bump dhis2 dependencies [DHIS2-17941]

- src/components/sectionList/SectionList.tsx
- src/pages/organisationUnits/list/OrganisationUnitList.tsx
Implements [DHIS2-18032](https://dhis2.atlassian.net/browse/DHIS2-18032)
Removing the select all checkbox in the header for othUnit list 
[DHIS2-18032]: https://dhis2.atlassian.net/browse/DHIS2-18032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: remove select all checkbox from org list

- src/components/sectionList/detailsPanel/DefaultDetailsPanel.tsx
- src/components/sectionList/detailsPanel/DetailsPanel.tsx
- src/components/sectionList/download/DownloadDialog.tsx
- src/components/sectionList/download/DownloadDialogContent.tsx
- src/pages/organisationUnits/List.spec.tsx
- src/pages/organisationUnits/list/OrganisationUnitList.tsx
- src/pages/organisationUnits/list/OrganisationUnitListActions.tsx
- src/pages/organisationUnits/list/OrganisationUnitRow.tsx
- src/types/generated/utility.ts
feat: add details panel to org list
> feat: add details panel to org list

- i18n/en.pot
- src/pages/organisationUnits/form/OrganisationUnitFormFields.tsx
- src/pages/organisationUnits/form/organisationUnitSchema.ts
Adds the fields `programs` and `dataSets`. Which allows the user to add the orgUnit to these related objects. This should only be available when the system setting `keyAllowObjectAssignment` is true. This can be enabled in `System settings`-app, under section `Access` - and enable the field `Allow assigning object to related objects during add or update`.
> fix(orgUnit): add reference assignment fields

- src/components/sectionList/listView/ManageListView.tsx
I encountered a bug where the `initialValues` was causing the the selected "columns" and "filters" to reset when you changed between the tabs in "Mange view"-dialog.
This should fix that, and cause the `initialValues` to be stable.
> fix(manageView): stable initialValues for form

- i18n/en.pot
- src/app/layout/Breadcrumb.module.css
- src/app/layout/Breadcrumb.spec.tsx
- src/app/layout/Breadcrumb.tsx
- src/app/routes/Router.tsx
- src/app/routes/types.ts
This mainly came about due to noticing that the `dataSet` design has a breadcrumb entry for `New data set`. The designs have some inconsistencies in regards to the breadcrumbs - but I decided to implement them. 
While doing this, I noticed that in the current implementation it would be non-trivial to pass a link for eg. `Edit` - because the ID is dynamic. Thus I decided to add some context to the callback of `crumb` in `handle` from `BreadCrumbs`-component. 
While doing this I also noticed that the `BreadCrumbItem` doesn't really have to know about the `section` - and thus decided to decouple it from `sections` - and just pass it a `to`-prop to decide the route.
- Added a parameter to `crumb`-callback in `handle` that takes `BreadcrumbMatch`-type, so the `pathname` can easily be reused …
> refactor(breadcrumbs): simplify and refactor breadcrumbs

- i18n/en.pot
- src/components/form/FormBase.tsx
- src/components/form/attributes/CustomAttributes.tsx
- src/components/form/fields/DateField.tsx
- src/lib/form/useOnSubmit.ts
- src/pages/categories/form/CategoryFormFields.tsx
- src/pages/categoryOptionCombos/form/CategoryOptionComboFormFields.tsx
- src/pages/categoryOptions/form/CategoryOptionFormFields.tsx
- src/pages/dataElementGroupSets/form/DataElementGroupSetFormFields.tsx
- src/pages/dataElementGroups/form/DataElementGroupFormFields.tsx
- src/pages/dataElements/form/DataElementFormFields.tsx
- src/pages/organisationUnits/form/ImageField.tsx
- src/pages/organisationUnits/form/OrganisationUnitFormFields.tsx
- fix gap between address  fields 
- change copies - attribute section title and subtitle + image upload help text
- fix attributes validation on edit - we need to format the values according to the form formatter before the validation
> fix: address feedback on org unit edit page

- src/components/metadataFormControls/OptionSetSelect/useInitialOptionQuery.ts
When going to edit a dataElement with an `optionSet` selected, an error would be thrown due to the `UseInitialOptionSet` using the singular name of `optionSet` on the data from `useOptionSetQuery`.
> fix(optionSetSelect): fix optionSet crashing with initialValue

- src/components/metadataFormControls/ModelTransfer/BaseModelTransfer.tsx
- src/lib/form/modelFormSchemas.ts
- src/lib/models/useFieldValidators.ts
- src/pages/categoryCombos/form/CategoriesField.tsx
- src/pages/categoryCombos/form/CategoryCombo.module.css
- src/pages/categoryCombos/form/CategoryComboFormFields.tsx
- src/pages/categoryCombos/form/categoryComboSchema.ts
- src/pages/categoryCombos/form/useIdenticalCategoryCombosQuery.tsx
- src/types/query.ts
Fixes: https://dhis2.atlassian.net/browse/DHIS2-18431
Implements more thorough validations and warnings for the user. Creating a `category combo` results in the system generating `category option combinations. This can easily take down the system if the creation of the combo results in too many option combinations. This PR addresses that through validations and warnings (which won't prevent saving). Note that I've used warnings to prevent conflicts in systems that are not really following best practices - eg. duplicate combinations. It would be annoying for such users to prevent saving/editing. 
* Fixes `useFieldValidators` that wasn't applied correctly. This should fix length validations for codefield.
* Removed "default" category from categories selector. 
* Erorr: Hard cap of 50k …
> feat(categoryCombo): add warning and validations

- src/components/sectionList/filters/filterSelectors/Filters.module.css
- src/components/sectionList/listView/ManageListView.tsx
- src/lib/constants/translatedModelProperties.ts
- src/lib/sectionList/listViews/sectionListViewsConfig.ts
- src/pages/dataElements/List.spec.tsx
- src/pages/dataElements/__mocks__/list/dataElementsMock.json
- src/pages/dataElements/__mocks__/list/filteredDataElementsMock.json
Fixes https://dhis2.atlassian.net/browse/DHIS2-18420 . Also includes some various cleanup of list descriptors, and manage list view.
* Fixes`IdentifiableFilter`-width after UI-upgrade.
* Also adds `lastUpdated` as part of the default available columns. 
* Use translated values for name and shortName
* Remove shortName from default columns
* This is not present on most objects, so Ive added this to objects that have it.
* Manage view dialog: hide "Filter"-tab if no available filters are present
* Manage view dialog: sort available columns/filters alphabetically. 
* Adds some missing translations for properties.
> fix(list): use translated values for name and shortName

- src/pages/categoryCombos/Edit.tsx
- src/pages/categoryCombos/form/CategoryComboFormFields.tsx
- src/pages/categoryCombos/form/categoryComboSchema.ts
Fixes https://dhis2.atlassian.net/browse/DHIS2-18432
In addition, I added a rule to disable `data dimension type` when editing. As you should not be able to change this after it's created.
> fix(categoryCombo): validation and load optionSize on initial load

- src/pages/categoryOptionGroupSets/form/CategoryOptionGroupSetFormFields.tsx
- src/pages/categoryOptionGroups/form/CategoryOptionGroupFormFields.tsx
Attributes-section was missing for `categoryOptionGroups` and `categoryOptionGroupSet`.
> fix(categoryOptionGroups): add custom attributesection to group/groupset

- src/pages/dataElementGroupSets/Edit.tsx
- src/pages/dataElementGroups/Edit.tsx
I noticed that when editing and saving `dataElementGroup` and `dataElementGroupSet` the navigation would be relative, and result in an error after saving because the page does not exist.
I'm unsure how and when this was introduced, because I'm pretty confident that this hasn't always been the case.
> fix: save navigation for dataElementGroup and -Sets

- src/components/form/fields/DescriptionField.tsx
- src/components/form/fields/NameField.tsx
- src/components/form/fields/ShortNameField.tsx
Fixes the comment in regards to `shortName` validation: https://dhis2.atlassian.net/browse/DHIS2-18538 
`shortName` used the wrong field to check against: probably due to copy/paste errors. I've updated the common fields `name`, and `shortName` to use the `useValidator` which uses the schema to decide which validation to apply to the fields. This should streamline the validations, and also fixes some discrepancies, because previously `unique` was always checked for `name` - but this is not necessarily correct. Eg. the schema does not define `unique: true` for `organisationUnit` and `dataSets`.
> fix(validation): use dynamic schema validator for common fields

- i18n/en.pot
- src/pages/organisationUnitGroups/Edit.spec.tsx
- src/pages/organisationUnitGroups/Edit.tsx
- src/pages/organisationUnitGroups/New.spec.tsx
- src/pages/organisationUnitGroups/New.tsx
- src/pages/organisationUnitGroups/form/OrganisationalUnitGroupFormFields.tsx
- src/pages/organisationUnitGroups/form/index.ts
- src/pages/organisationUnitGroups/form/organisationUnitGroupSchema.ts
Implements https://dhis2.atlassian.net/browse/DHIS2-18879 and https://dhis2.atlassian.net/browse/DHIS2-18878
> feat: org unit group forms

- src/pages/organisationUnits/form/organisationUnitSchema.ts
fixes comment in https://dhis2.atlassian.net/browse/DHIS2-17899?focusedCommentId=208064. Validation fails just now as the types do not match case.
> fix: geometry types to match case

- src/pages/dataSetsWip/form/PeriodsFormContents.tsx
- src/pages/dataSetsWip/form/dataSetFormSchema.ts
This change prevents users to fill in decimal numbers for open-period-after-co-end-date dield in datasets
> fix: open periods after cat option end date should not allow decimals

- src/components/sectionList/SectionListWrapper.tsx
- src/components/sectionList/listActions/DefaultListActions.tsx
Fixes https://dhis2.atlassian.net/browse/DHIS2-18617
First I just did a `clearAll`, but we might not want to remove other selections? So I decided to pass the model, so we can remove just the deleted model.
> fix(list): remove deleted model from selected

- src/components/fields/index.ts
- src/components/fields/valueType/FormFieldByValueType.tsx
- src/components/fields/valueType/ValueTypeRenderer.tsx
- src/components/fields/valueType/index.ts
- src/components/fields/valueType/types.ts
- src/components/fields/valueType/validateByValueType.ts
- src/components/form/attributes/CustomAttributes.tsx
- src/components/merge/MergeFieldsBase.tsx
- src/components/metadataFormControls/ModelMultiSelect/ModelMultiSelectField.tsx
- src/components/metadataFormControls/ModelSingleSelect/ModelSingleSelect.test.tsx
- src/components/metadataFormControls/ModelSingleSelect/ModelSingleSelect.tsx
- src/components/metadataFormControls/ModelSingleSelect/ModelSingleSelectField.tsx
- src/pages/dataSetsWip/form/CategoryComboField.tsx
Fixes [DHIS2-18194](https://dhis2.atlassian.net/browse/DHIS2-18194)
This implements more `valueType`-fields for attributes, but most importantly falls back to a simple input field instead of throwing an error. 
I wanted to decouple the valueTypes renderer from attributes itself. This is because `valueTypes` can also be used in eg. options of optionSets, rather than just for attributes - so I've moved this to it's own "concept/folder".
I also wanted to decouple the rendered field from `final-form`, eg. instead of rendering fields bound to the form, the `ValueTypeRenderer` is not connected to the form (much like FF fields from UI). 
I've added a convenient wrapper to final form with `FormFieldByValueType`-component. 
[DHIS2-18194]: …
> fix: add missing attribute valueTypes

- cypress/e2e/dataElements/New.spec.ts
- src/components/metadataFormControls/ModelTransfer/ModelTransferField.tsx
- src/pages/dataSetsWip/Edit.tsx
- src/pages/dataSetsWip/form/AdvancedFormContents.tsx
- src/pages/dataSetsWip/form/dataSetFormSchema.ts
This PR adds the Advanced section for Data Set forms: [DHIS2-18710](https://dhis2.atlassian.net/browse/DHIS2-18710)
**Notes:**
- specified on the ticket, but I haven't paid much attention to styling
- _notification recipients_: in the design document shows that you can select multiple user groups but the api seems to expect one user group, so I have updated to use a single select. There was also some help text in the design document that did not seem relevant, so I have removed it.
- _legend sets_: I tried looking in the documentation, CoP, etc., to see what these are supposed to do and couldn't figure it out 🤷‍♂️. I've put them in with the same options as in the old app (the old app expressly filtered out default legend set in the query, but I didn't see why this would be necessary). …
> feat: data sets advanced [DHIS2-18710]

- i18n/en.pot
- src/pages/dataSetsWip/form/dataInputPeriods/useGetPeriods.ts
This PR fixes an issue identified in testing (https://dhis2.atlassian.net/browse/DHIS2-18708?focusedCommentId=210546)
Certain calendars were failing because a valid default year was not being provided to period calculations before user selection.
> fix: handle unselected year for period calcs

- i18n/en.pot
- src/pages/dataSetsWip/form/CompulsoryDataElementsTransfer.tsx
Allows all selection on compulsory data element operands transfer (fixes testing issue: https://dhis2.atlassian.net/browse/DHIS2-18707?focusedCommentId=210746)
> fix: add max selections to compuslory data element operands

- src/app/routes/Router.tsx
- src/app/routes/SyncURLWithGlobalShell.tsx
- src/app/routes/SyncUrlWithGlobalShell.tsx
`react-router@6+` does not fire `popstate` for `pushState/replaceState`. The `global shell` [is listening](https://github.com/dhis2/global-shell-app/blob/main/src/components/PluginLoader.jsx#L45) to `popstate`-events to update the url in the parent frame. 
This PR listens to router changes from `useLocation` and creates a `popstate` event so that the global routes can update the URL in the browser. 
Previous versions of `react-router` did fire `popstate` on push/replace, there's some background of why this was changed here: https://github.com/remix-run/react-router/blob/44472360ec9ea045008f453280bb749cb58e90ea/decisions/0005-remixing-react-router.md#inline-the-history-library-into-the-router .
> fix: sync route updates with global shell

- src/components/SearchableSingleSelect/SearchableSingleSelect.module.css
- src/components/SearchableSingleSelect/SearchableSingleSelect.tsx
- src/components/merge/MergeFieldsBase.tsx
- src/components/metadataFormControls/ModelSingleSelect/BaseModelSingleSelect.tsx
- src/components/metadataFormControls/ModelSingleSelect/ModelSingleSelect.tsx
- src/components/metadataFormControls/ModelSingleSelect/ModelSingleSelectField.tsx
- src/pages/categoryOptions/merge/CategoryOptionMergeFormFields.tsx
- src/pages/indicatorTypes/merge/IndicatorTypeMergeFormFields.tsx
- src/pages/indicators/merge/IndicatorMergeFormFields.tsx
See https://dhis2.atlassian.net/browse/BETA-348
This addresses a couple of issues:
- As per the ticket's suggestion, this adds some text to make it clear that there are no selectable options when you have selected all items as source items:
- Adds an all purpose "No matches" text when there are no matches after filtering:
- Adds some logic in a useEffect to refresh target information until the desired pageCount of filtered results have been found (or there are no more pages left). (This fixes a bug where if you reloaded the merge page, you would get an infinite loader / not 10 initial matches for the target)
> fix: display information when no target is available [BETA-348]

- src/components/form/DefaultFormErrorNotice.module.css
- src/components/form/DefaultFormErrorNotice.tsx
- src/components/form/useFormStateErrors.ts
- src/components/sectionedForm/SectionedFormErrorNotice.tsx
- src/lib/errors/apiErrorSchemas.ts
- src/lib/errors/apiErrors.ts
- src/lib/errors/errors.ts
- src/lib/errors/index.ts
- src/lib/form/createFormError.ts
- src/lib/form/useCreateModel.ts
- src/lib/form/useOnSubmit.ts
- src/lib/form/usePatchModel.ts
- src/pages/organisationUnits/Edit.tsx
- src/pages/organisationUnits/New.tsx
Implements https://dhis2.atlassian.net/browse/DHIS2-18984 
Refactor error-handling, and stores the full error in the form-state instead of just a string of the error on the root of the server error.
Implemented an unified "error"-type `ApiErrorReport`, since the backend has multiple error-structures. We parse the different structure into this unified type, so it's easier for the client to consume the error. Currently the parsing is implemented using `zod`-schemas, these schemas are generated using [kubb](https://kubb.dev/) and openAPI. The relevant schemas has been manually copied, but we may want to use the same tool to generate and publish types and `zod`-schemas later. This work is related to the openAPI type-generation that I worked on before christmas that was postponed. 
There was …
> feat(forms): improve display of errors

- src/app/sidebar/SidebarLinks.ts
Hides the 'other' section (including program disaggregations) in sidebar while this is work in progress.
**Before**
**After**
> fix: hide other section

- src/pages/programDisaggregations/Edit.tsx
- src/pages/programDisaggregations/form/ProgramIndicatorMapping.module.css
- src/pages/programDisaggregations/form/ProgramIndicatorMappingSection.tsx
- src/pages/programDisaggregations/form/programDisaggregationSchema.ts
- src/pages/programDisaggregations/form/useUpdateProgramIndicatorMutation.ts
See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-19334
This PR adds the `aggregateExportDataElement` field as per the specs' prototype. There is no validation on the field per design and user is free to enter anything (e.g. because they may be using code for the export on an external system).
> feat: add aggregateExportDataElement [DHIS2-19334]

- src/pages/programDisaggregations/form/DissaggregationCategories.tsx
- src/pages/programDisaggregations/form/apiResponseToFormValues.ts
This PR is a follow up to discussion yesterday on how to handle UI given that the backend does not necessarily return categoryMappings in a fixed order.
- sorts the category mappings in the initial values alphabetically by mapping name
- presents the soft delete option for individual mapping when there are two or more non-soft deleted category mappings for a given category
> feat: sort initial category mappings [DHIS2-19246]

- src/pages/programDisaggregations/form/CategoriesSelector.tsx
- src/pages/programDisaggregations/form/CategoryMapping.tsx
- src/pages/programDisaggregations/form/ProgramIndicatorMappingSection.tsx
There was a mismatch between the field-filters for the `categoryCombo` selectors, and we thus had missing information when selecting a new catcombo, compared to loading the form-state. There were actually two bugs; one due to missing categoryOptions - so the options were not in the state after selecting. And one with missing `dataDimensionType` - so the option was filtered out in `calculatedCategories`.
> fix: fix crash when adding a suggested category combo

- src/pages/programDisaggregations/form/useOnSubmit.ts
See https://dhis2.atlassian.net/browse/DHIS2-19729
Soft deleted individual mappings were not being removed on save. This ticket updates the logic for cleaning up categoryMappings to filter out soft deleted individual mappings
> fix: remove soft deleted category mappings [DHIS2-19695]

- package.json
- src/components/sectionList/SectionListWrapper.tsx
- yarn.lock
See https://dhis2.atlassian.net/browse/DHIS2-18430
This PR updates the @dhis2/ui dependency to pick up the changes to the sharing dialog (https://github.com/dhis2/ui/pull/1694) that allow you to prevent users from removing their own metadata write access (by setting `preventUsersFromRemovingMetadataWriteAccess: true` on SharingDialog component).
As an example, if I log in with `alinana` user and I update sharing for a data element and first add read/write access to `alinana` then remove public access, if I then try to set `alinana`'s access to "View only", I will get an alert and the post will not be executed:
I've not updated any tests in the maintenance app as the updated sharing dialog component is tested in the dhis2/ui library, I think we generally don't test the internal workings of …
> feat: prevent users from removing sharing [DHIS2-18430]

- src/pages/attributes/form/AttributeTypeComponent.tsx
@karolinelien pointed out that the ticket https://dhis2.atlassian.net/browse/DHIS2-19842 called for the attribute objects to be searchable, so I've added that:
> fix: make attribute object selections filterable

- i18n/en.pot
- src/pages/dataSetsWip/form/DisplayOptionsField.tsx
- src/pages/dataSetsWip/form/dataEntryForm/sectionForm/DataSetSectionFormContents.tsx
- src/pages/indicators/Form.spec.tsx
This PR fixes two issues:
- adds non-default nsSeparator to strings containing a `:`, such that they can be properly scanned by i18next-scanner
- increases time out on indicator form tests (they run fine locally but timeout in CI run)
> fix: ns separator and indicator form timeouts

- src/pages/dataSetNotificationTemplates/Edit.tsx
fixes issue pointed out here https://dhis2.atlassian.net/browse/DHIS2-1878?focusedCommentId=222513
Forgot to add property in edit page, so it didn't appear when you opened up for edit.
This PR fixes that:
> fix: add property for edit

- src/lib/constants/translatedModelProperties.ts
- src/lib/sectionList/listViews/sectionListViewsConfig.ts
See https://dhis2.atlassian.net/browse/DHIS2-17306
Adds `aggregateExportDataElement` in programIndicator list.
> fix: add aggregateExportDataElement into list
